// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
	"time"
)

type BlogSetting struct {
	Key       string         `json:"key"`
	Value     sql.NullString `json:"value"`
	ValueType string         `json:"value_type"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type MediaVisibilityLog struct {
	ID        int64         `json:"id"`
	MediaID   int64         `json:"media_id"`
	IsPublic  int64         `json:"is_public"`
	ChangedAt time.Time     `json:"changed_at"`
	PostID    sql.NullInt64 `json:"post_id"`
}

type Medium struct {
	ID            int64          `json:"id"`
	Filename      string         `json:"filename"`
	OriginalPath  string         `json:"original_path"`
	ThumbnailPath sql.NullString `json:"thumbnail_path"`
	FileType      string         `json:"file_type"`
	MimeType      string         `json:"mime_type"`
	FileSize      int64          `json:"file_size"`
	Width         sql.NullInt64  `json:"width"`
	Height        sql.NullInt64  `json:"height"`
	PostID        sql.NullInt64  `json:"post_id"`
	UploadedAt    time.Time      `json:"uploaded_at"`
	Checksum      string         `json:"checksum"`
	AltText       sql.NullString `json:"alt_text"`
	Caption       sql.NullString `json:"caption"`
	IsPublic      int64          `json:"is_public"`
}

type Post struct {
	ID               int64          `json:"id"`
	Title            string         `json:"title"`
	Slug             string         `json:"slug"`
	Content          string         `json:"content"`
	Excerpt          sql.NullString `json:"excerpt"`
	Formatter        string         `json:"formatter"`
	Status           string         `json:"status"`
	IsFeatured       bool           `json:"is_featured"`
	ViewCount        int64          `json:"view_count"`
	PublishedAt      sql.NullTime   `json:"published_at"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	AuthorID         int64          `json:"author_id"`
	ThumbnailPath    sql.NullString `json:"thumbnail_path"`
	MetaDescription  sql.NullString `json:"meta_description"`
	PreviewToken     sql.NullString `json:"preview_token"`
	PreviewExpiresAt sql.NullTime   `json:"preview_expires_at"`
}

type PostTag struct {
	PostID int64 `json:"post_id"`
	TagID  int64 `json:"tag_id"`
}

type Session struct {
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
	Token        string         `json:"token"`
	IpAddress    string         `json:"ip_address"`
	UserAgent    string         `json:"user_agent"`
	Location     sql.NullString `json:"location"`
	CreatedAt    time.Time      `json:"created_at"`
	ExpiresAt    time.Time      `json:"expires_at"`
	LastActivity time.Time      `json:"last_activity"`
}

type Tag struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	CustomUrl   sql.NullString `json:"custom_url"`
	SortOrder   sql.NullInt64  `json:"sort_order"`
	PostCount   int64          `json:"post_count"`
	CreatedAt   time.Time      `json:"created_at"`
}

type TagLocation struct {
	ID        int64   `json:"id"`
	TagID     int64   `json:"tag_id"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type TagRelationship struct {
	ParentID int64 `json:"parent_id"`
	ChildID  int64 `json:"child_id"`
}

type User struct {
	ID           int64          `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	DisplayName  string         `json:"display_name"`
	AvatarPath   sql.NullString `json:"avatar_path"`
	CreatedAt    time.Time      `json:"created_at"`
	LastLogin    sql.NullTime   `json:"last_login"`
}
