// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"database/sql"
	"time"
)

type ApiKey struct {
	ID         int64        `json:"id"`
	UserID     int64        `json:"user_id"`
	Name       string       `json:"name"`
	KeyHash    string       `json:"key_hash"`
	Prefix     string       `json:"prefix"`
	CreatedAt  time.Time    `json:"created_at"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	RevokedAt  sql.NullTime `json:"revoked_at"`
}

type BlogSecret struct {
	Key       string         `json:"key"`
	Value     sql.NullString `json:"value"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type BlogSetting struct {
	Key       string         `json:"key"`
	Value     sql.NullString `json:"value"`
	ValueType string         `json:"value_type"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type MediaVisibilityLog struct {
	ID        int64         `json:"id"`
	MediaID   int64         `json:"media_id"`
	IsPublic  int64         `json:"is_public"`
	ChangedAt time.Time     `json:"changed_at"`
	PostID    sql.NullInt64 `json:"post_id"`
}

type Medium struct {
	ID               int64          `json:"id"`
	Filename         string         `json:"filename"`
	OriginalPath     string         `json:"original_path"`
	ThumbnailPath    sql.NullString `json:"thumbnail_path"`
	FileType         string         `json:"file_type"`
	MimeType         string         `json:"mime_type"`
	FileSize         int64          `json:"file_size"`
	Width            sql.NullInt64  `json:"width"`
	Height           sql.NullInt64  `json:"height"`
	PostID           sql.NullInt64  `json:"post_id"`
	UploadedAt       time.Time      `json:"uploaded_at"`
	Checksum         string         `json:"checksum"`
	AltText          sql.NullString `json:"alt_text"`
	Caption          sql.NullString `json:"caption"`
	Metadata         sql.NullString `json:"metadata"`
	OriginalMetadata sql.NullString `json:"original_metadata"`
	IsPublic         int64          `json:"is_public"`
}

type Post struct {
	ID                   int64          `json:"id"`
	Title                string         `json:"title"`
	Slug                 string         `json:"slug"`
	Content              string         `json:"content"`
	Excerpt              sql.NullString `json:"excerpt"`
	Formatter            string         `json:"formatter"`
	Status               string         `json:"status"`
	Type                 string         `json:"type"`
	IsFeatured           bool           `json:"is_featured"`
	ViewCount            int64          `json:"view_count"`
	PublishedAt          sql.NullTime   `json:"published_at"`
	ScheduledAt          sql.NullTime   `json:"scheduled_at"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	AuthorID             int64          `json:"author_id"`
	ThumbnailPath        sql.NullString `json:"thumbnail_path"`
	MetaDescription      sql.NullString `json:"meta_description"`
	PreviewToken         sql.NullString `json:"preview_token"`
	PreviewExpiresAt     sql.NullTime   `json:"preview_expires_at"`
	DeletedAt            sql.NullTime   `json:"deleted_at"`
	Css                  string         `json:"css"`
	ImmersiveMode        string         `json:"immersive_mode"`
	InstagramShare       bool           `json:"instagram_share"`
	InstagramStatus      string         `json:"instagram_status"`
	InstagramMediaID     sql.NullString `json:"instagram_media_id"`
	InstagramPublishedAt sql.NullTime   `json:"instagram_published_at"`
	InstagramError       sql.NullString `json:"instagram_error"`
}

type PostTag struct {
	PostID int64 `json:"post_id"`
	TagID  int64 `json:"tag_id"`
}

type Session struct {
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
	Token        string         `json:"token"`
	IpAddress    string         `json:"ip_address"`
	UserAgent    string         `json:"user_agent"`
	Location     sql.NullString `json:"location"`
	CreatedAt    time.Time      `json:"created_at"`
	ExpiresAt    time.Time      `json:"expires_at"`
	LastActivity time.Time      `json:"last_activity"`
}

type Tag struct {
	ID               int64           `json:"id"`
	Name             string          `json:"name"`
	Slug             string          `json:"slug"`
	Description      sql.NullString  `json:"description"`
	Kind             string          `json:"kind"`
	Hidden           bool            `json:"hidden"`
	HidesPosts       bool            `json:"hides_posts"`
	NavOrder         sql.NullInt64   `json:"nav_order"`
	InBreadcrumbs    bool            `json:"in_breadcrumbs"`
	ShowRelated      bool            `json:"show_related"`
	InAncestorFlyout bool            `json:"in_ancestor_flyout"`
	Latitude         sql.NullFloat64 `json:"latitude"`
	Longitude        sql.NullFloat64 `json:"longitude"`
	PostCount        int64           `json:"post_count"`
	CreatedAt        time.Time       `json:"created_at"`
}

type TagRelationship struct {
	ParentID  int64         `json:"parent_id"`
	ChildID   int64         `json:"child_id"`
	SortOrder sql.NullInt64 `json:"sort_order"`
}

type User struct {
	ID           int64          `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	DisplayName  string         `json:"display_name"`
	AvatarPath   sql.NullString `json:"avatar_path"`
	CreatedAt    time.Time      `json:"created_at"`
	LastLogin    sql.NullTime   `json:"last_login"`
}

type WebauthnCredential struct {
	ID             int64        `json:"id"`
	UserID         int64        `json:"user_id"`
	CredentialID   []byte       `json:"credential_id"`
	PublicKey      []byte       `json:"public_key"`
	Aaguid         []byte       `json:"aaguid"`
	SignCount      int64        `json:"sign_count"`
	BackupEligible int64        `json:"backup_eligible"`
	BackupState    int64        `json:"backup_state"`
	CreatedAt      time.Time    `json:"created_at"`
	LastUsedAt     sql.NullTime `json:"last_used_at"`
}
