// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddPostViewCount(ctx context.Context, arg AddPostViewCountParams) error
	AddTagRelationship(ctx context.Context, arg AddTagRelationshipParams) error
	AddTagToPost(ctx context.Context, arg AddTagToPostParams) error
	BulkPublishScheduledPosts(ctx context.Context) ([]Post, error)
	ClearPostTags(ctx context.Context, postID int64) error
	ClearTagRelationships(ctx context.Context, arg ClearTagRelationshipsParams) error
	CountMedia(ctx context.Context, arg CountMediaParams) (int64, error)
	CountPostsByTag(ctx context.Context, arg CountPostsByTagParams) (int64, error)
	CountTrashedPosts(ctx context.Context) (int64, error)
	// API KEYS
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error
	DeleteCarouselByBlockKey(ctx context.Context, arg DeleteCarouselByBlockKeyParams) error
	DeleteCarouselTemplate(ctx context.Context, slug string) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteMedia(ctx context.Context, id int64) error
	DeletePost(ctx context.Context, arg DeletePostParams) error
	DeletePostTagsByTag(ctx context.Context, tagID int64) error
	DeleteSetting(ctx context.Context, key string) error
	DeleteTag(ctx context.Context, id int64) error
	DeleteUserSessions(ctx context.Context, arg DeleteUserSessionsParams) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error)
	// CAROUSELS
	// One Carousel Studio document per carousel block, keyed (post_id, block_key):
	// a post may hold several independent carousels. doc is opaque JSON, stored and
	// returned verbatim; the schema lives in frontend/src/plugins/carousel/document.js.
	//
	// ListCarouselsByPostID names its columns and omits doc for the same reason
	// ListCarouselTemplates does: the caller wants to know which of a post's blocks
	// have a stored document, not to load every document to find out. Ordered by id,
	// so its first row is the post's oldest carousel -- which is what an unkeyed
	// request resolves to.
	GetCarouselByBlockKey(ctx context.Context, arg GetCarouselByBlockKeyParams) (Carousel, error)
	GetCarouselTemplateBySlug(ctx context.Context, slug string) (CarouselTemplate, error)
	GetFirstUser(ctx context.Context) (User, error)
	// MEDIA
	GetMedia(ctx context.Context, id int64) (Medium, error)
	GetMediaByChecksum(ctx context.Context, checksum string) (Medium, error)
	GetMediaByPostID(ctx context.Context, postID sql.NullInt64) ([]Medium, error)
	// POSTS
	GetPost(ctx context.Context, id int64) (Post, error)
	GetPostAnalytics(ctx context.Context) (GetPostAnalyticsRow, error)
	GetPostBySlug(ctx context.Context, slug string) (Post, error)
	GetPostsByTag(ctx context.Context, arg GetPostsByTagParams) ([]Post, error)
	// SECRETS
	GetSecret(ctx context.Context, key string) (BlogSecret, error)
	GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error)
	// SETTINGS
	GetSetting(ctx context.Context, key string) (BlogSetting, error)
	GetStorageUsage(ctx context.Context) (sql.NullFloat64, error)
	// TAGS
	GetTag(ctx context.Context, id int64) (Tag, error)
	GetTagBySlug(ctx context.Context, slug string) (Tag, error)
	GetTagChildren(ctx context.Context, parentID int64) ([]Tag, error)
	// HIERARCHY
	GetTagParents(ctx context.Context, childID int64) ([]Tag, error)
	GetTagsForPost(ctx context.Context, postID int64) ([]Tag, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserSessions(ctx context.Context, userID int64) ([]Session, error)
	IncrementPostViewCount(ctx context.Context, id int64) error
	ListAPIKeysByUser(ctx context.Context, userID int64) ([]ApiKey, error)
	// Every stored carousel's address, for the orphan sweep to check against each
	// post's own content: a row whose (post_id, block_key) matches no fence there
	// is orphaned (see api/cmd/api/orphansweep.go).
	ListAllCarouselBlockKeys(ctx context.Context) ([]ListAllCarouselBlockKeysRow, error)
	// CAROUSEL TEMPLATES
	// A reusable carousel envelope, keyed by slug. doc is the same opaque JSON as
	// carousels.doc. ListCarouselTemplates deliberately names its columns and
	// omits doc: a template inlines its assets as data: URLs, so SELECT * here
	// would pull every asset of every template to draw a list of names.
	ListCarouselTemplates(ctx context.Context) ([]ListCarouselTemplatesRow, error)
	ListCarouselsByPostID(ctx context.Context, postID int64) ([]ListCarouselsByPostIDRow, error)
	ListMedia(ctx context.Context, arg ListMediaParams) ([]Medium, error)
	// Every post's id and content, deleted or not: a trashed post can still be
	// restored, so its fences stay live for the orphan-carousel sweep.
	ListPostIDsAndContent(ctx context.Context) ([]ListPostIDsAndContentRow, error)
	ListSettings(ctx context.Context) ([]BlogSetting, error)
	ListTags(ctx context.Context, includeEmptyFilter interface{}) ([]Tag, error)
	ListTrashedPosts(ctx context.Context, arg ListTrashedPostsParams) ([]Post, error)
	MergePostTags(ctx context.Context, arg MergePostTagsParams) error
	MergeTagChildren(ctx context.Context, arg MergeTagChildrenParams) error
	MergeTagParents(ctx context.Context, arg MergeTagParentsParams) error
	PublishPost(ctx context.Context, id int64) (Post, error)
	RemoveTagFromPost(ctx context.Context, arg RemoveTagFromPostParams) error
	RemoveTagRelationship(ctx context.Context, arg RemoveTagRelationshipParams) error
	RestorePost(ctx context.Context, arg RestorePostParams) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
	SetPostPreviewToken(ctx context.Context, arg SetPostPreviewTokenParams) error
	SoftDeletePost(ctx context.Context, arg SoftDeletePostParams) error
	TouchAPIKeyLastUsed(ctx context.Context, id int64) error
	UpdateAllTagPostCounts(ctx context.Context) error
	UpdateMedia(ctx context.Context, arg UpdateMediaParams) (Medium, error)
	UpdateMediaFilename(ctx context.Context, arg UpdateMediaFilenameParams) (Medium, error)
	UpdateMediaMetadata(ctx context.Context, arg UpdateMediaMetadataParams) (Medium, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdatePostInstagramStatus(ctx context.Context, arg UpdatePostInstagramStatusParams) error
	UpdateSessionActivity(ctx context.Context, id int64) error
	UpdateSetting(ctx context.Context, arg UpdateSettingParams) (BlogSetting, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
	UpdateTagPostCount(ctx context.Context, id int64) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserLogin(ctx context.Context, id int64) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertCarousel(ctx context.Context, arg UpsertCarouselParams) (Carousel, error)
	UpsertCarouselTemplate(ctx context.Context, arg UpsertCarouselTemplateParams) (CarouselTemplate, error)
	UpsertSecret(ctx context.Context, arg UpsertSecretParams) error
	WithdrawPost(ctx context.Context, id int64) (Post, error)
}

var _ Querier = (*Queries)(nil)
