// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package models

import (
	"context"
	"database/sql"
	"time"
)

const addPostViewCount = `-- name: AddPostViewCount :exec
UPDATE posts
SET view_count = view_count + ?
WHERE id = ?
`

type AddPostViewCountParams struct {
	ViewCount int64 `json:"view_count"`
	ID        int64 `json:"id"`
}

func (q *Queries) AddPostViewCount(ctx context.Context, arg AddPostViewCountParams) error {
	_, err := q.db.ExecContext(ctx, addPostViewCount, arg.ViewCount, arg.ID)
	return err
}

const addTagRelationship = `-- name: AddTagRelationship :exec
INSERT OR IGNORE INTO tag_relationships (parent_id, child_id)
VALUES (?, ?)
`

type AddTagRelationshipParams struct {
	ParentID int64 `json:"parent_id"`
	ChildID  int64 `json:"child_id"`
}

func (q *Queries) AddTagRelationship(ctx context.Context, arg AddTagRelationshipParams) error {
	_, err := q.db.ExecContext(ctx, addTagRelationship, arg.ParentID, arg.ChildID)
	return err
}

const addTagToPost = `-- name: AddTagToPost :exec
INSERT OR IGNORE INTO post_tags (post_id, tag_id)
VALUES (?, ?)
`

type AddTagToPostParams struct {
	PostID int64 `json:"post_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) AddTagToPost(ctx context.Context, arg AddTagToPostParams) error {
	_, err := q.db.ExecContext(ctx, addTagToPost, arg.PostID, arg.TagID)
	return err
}

const bulkPublishScheduledPosts = `-- name: BulkPublishScheduledPosts :many
UPDATE posts
SET status = 'published',
    published_at = COALESCE(scheduled_at, CURRENT_TIMESTAMP),
    scheduled_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE status = 'scheduled' AND scheduled_at IS NOT NULL AND scheduled_at <= CURRENT_TIMESTAMP
AND deleted_at IS NULL
RETURNING id, title, slug, content, excerpt, formatter, status, type, is_featured, view_count, published_at, scheduled_at, created_at, updated_at, author_id, thumbnail_path, meta_description, preview_token, preview_expires_at, deleted_at, css, immersive_mode, instagram_share, instagram_status, instagram_media_id, instagram_published_at, instagram_error, instagram_id
`

func (q *Queries) BulkPublishScheduledPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, bulkPublishScheduledPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Excerpt,
			&i.Formatter,
			&i.Status,
			&i.Type,
			&i.IsFeatured,
			&i.ViewCount,
			&i.PublishedAt,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID,
			&i.ThumbnailPath,
			&i.MetaDescription,
			&i.PreviewToken,
			&i.PreviewExpiresAt,
			&i.DeletedAt,
			&i.Css,
			&i.ImmersiveMode,
			&i.InstagramShare,
			&i.InstagramStatus,
			&i.InstagramMediaID,
			&i.InstagramPublishedAt,
			&i.InstagramError,
		&i.InstagramID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearPostTags = `-- name: ClearPostTags :exec
DELETE FROM post_tags
WHERE post_id = ?
`

func (q *Queries) ClearPostTags(ctx context.Context, postID int64) error {
	_, err := q.db.ExecContext(ctx, clearPostTags, postID)
	return err
}

const clearTagRelationships = `-- name: ClearTagRelationships :exec
DELETE FROM tag_relationships
WHERE parent_id = ? OR child_id = ?
`

type ClearTagRelationshipsParams struct {
	ParentID int64 `json:"parent_id"`
	ChildID  int64 `json:"child_id"`
}

func (q *Queries) ClearTagRelationships(ctx context.Context, arg ClearTagRelationshipsParams) error {
	_, err := q.db.ExecContext(ctx, clearTagRelationships, arg.ParentID, arg.ChildID)
	return err
}

const countMedia = `-- name: CountMedia :one
SELECT COUNT(*) FROM media
WHERE (CASE WHEN ?1 THEN file_type = ?2 ELSE 1=1 END)
`

type CountMediaParams struct {
	TypeFilter interface{} `json:"type_filter"`
	FileType   string      `json:"file_type"`
}

func (q *Queries) CountMedia(ctx context.Context, arg CountMediaParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMedia, arg.TypeFilter, arg.FileType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPosts = `-- name: CountPosts :one
WITH RECURSIVE h(id) AS (
    SELECT id FROM tags WHERE hides_posts = 1
    UNION
    SELECT tr.child_id FROM tag_relationships tr JOIN h ON tr.parent_id = h.id
)
SELECT COUNT(*) FROM posts p
WHERE
    p.deleted_at IS NULL
    AND p.type != 'page'
    AND (CASE WHEN ?1 THEN p.status = ?2 ELSE 1=1 END)
    AND (CASE WHEN ?3 THEN p.is_featured = 1 ELSE 1=1 END)
    AND (CASE
        WHEN ?4 THEN 1=1
        WHEN ?5 THEN p.status IN ('published', 'hidden')
        ELSE p.status = 'published'
    END)

    AND (CASE
        WHEN ?4 THEN 1=1
        WHEN ?5 THEN 1=1
        ELSE p.id NOT IN (
            SELECT pt.post_id FROM post_tags pt
            WHERE pt.tag_id IN (SELECT id FROM h)
        )
    END)
`

type CountPostsParams struct {
	StatusFilter   interface{} `json:"status_filter"`
	Status         string      `json:"status"`
	FeaturedFilter interface{} `json:"featured_filter"`
	IncludeDrafts  interface{} `json:"include_drafts"`
	IncludeHidden  interface{} `json:"include_hidden"`
	// IncludePages, when true, keeps type=page rows in results (admin views).
	IncludePages bool `json:"include_pages"`
}

func (q *Queries) CountPosts(ctx context.Context, arg CountPostsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPosts,
		arg.StatusFilter,
		arg.Status,
		arg.FeaturedFilter,
		arg.IncludeDrafts,
		arg.IncludeHidden,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPostsByTag = `-- name: CountPostsByTag :one
WITH RECURSIVE h(id) AS (
    SELECT id FROM tags WHERE hides_posts = 1
    UNION
    SELECT tr.child_id FROM tag_relationships tr JOIN h ON tr.parent_id = h.id
)
SELECT COUNT(*) FROM posts p
JOIN post_tags pt ON p.id = pt.post_id
WHERE pt.tag_id = ?1
AND p.deleted_at IS NULL
AND (CASE
    WHEN ?2 THEN 1=1
    WHEN ?3 THEN
        p.status = 'published'
        AND NOT EXISTS (
            SELECT 1 FROM post_tags pt2
            WHERE pt2.post_id = p.id AND pt2.tag_id IN (SELECT id FROM h)
        )
    ELSE p.status IN ('published', 'hidden')
END)
`

type CountPostsByTagParams struct {
	TagID               int64       `json:"tag_id"`
	IncludeDrafts       interface{} `json:"include_drafts"`
	PublishedOnlyFilter interface{} `json:"published_only_filter"`
}

func (q *Queries) CountPostsByTag(ctx context.Context, arg CountPostsByTagParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPostsByTag, arg.TagID, arg.IncludeDrafts, arg.PublishedOnlyFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrashedPosts = `-- name: CountTrashedPosts :one
SELECT COUNT(*) FROM posts
WHERE deleted_at IS NOT NULL
`

func (q *Queries) CountTrashedPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTrashedPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one

INSERT INTO api_keys (
    user_id, name, key_hash, prefix, expires_at, created_at
) VALUES (
    ?, ?, ?, ?, ?, CURRENT_TIMESTAMP
)
RETURNING id, user_id, name, key_hash, prefix, created_at, last_used_at, expires_at, revoked_at
`

type CreateAPIKeyParams struct {
	UserID    int64        `json:"user_id"`
	Name      string       `json:"name"`
	KeyHash   string       `json:"key_hash"`
	Prefix    string       `json:"prefix"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

// API KEYS
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.Prefix,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
    filename, original_path, thumbnail_path, file_type, mime_type, file_size, width, height, post_id, checksum, alt_text, caption, metadata, original_metadata, uploaded_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, filename, original_path, thumbnail_path, file_type, mime_type, file_size, width, height, post_id, uploaded_at, checksum, alt_text, caption, metadata, original_metadata, is_public
`

type CreateMediaParams struct {
	Filename         string         `json:"filename"`
	OriginalPath     string         `json:"original_path"`
	ThumbnailPath    sql.NullString `json:"thumbnail_path"`
	FileType         string         `json:"file_type"`
	MimeType         string         `json:"mime_type"`
	FileSize         int64          `json:"file_size"`
	Width            sql.NullInt64  `json:"width"`
	Height           sql.NullInt64  `json:"height"`
	PostID           sql.NullInt64  `json:"post_id"`
	Checksum         string         `json:"checksum"`
	AltText          sql.NullString `json:"alt_text"`
	Caption          sql.NullString `json:"caption"`
	Metadata         sql.NullString `json:"metadata"`
	OriginalMetadata sql.NullString `json:"original_metadata"`
	UploadedAt       time.Time      `json:"uploaded_at"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.Filename,
		arg.OriginalPath,
		arg.ThumbnailPath,
		arg.FileType,
		arg.MimeType,
		arg.FileSize,
		arg.Width,
		arg.Height,
		arg.PostID,
		arg.Checksum,
		arg.AltText,
		arg.Caption,
		arg.Metadata,
		arg.OriginalMetadata,
		arg.UploadedAt,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalPath,
		&i.ThumbnailPath,
		&i.FileType,
		&i.MimeType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.PostID,
		&i.UploadedAt,
		&i.Checksum,
		&i.AltText,
		&i.Caption,
		&i.Metadata,
		&i.OriginalMetadata,
		&i.IsPublic,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    title, slug, content, excerpt, formatter, status, type, is_featured, author_id, thumbnail_path, meta_description, view_count, published_at, scheduled_at, created_at, updated_at, css, immersive_mode, instagram_share
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, 0, (CASE WHEN ?6 = 'published' THEN CURRENT_TIMESTAMP ELSE NULL END), ?12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ?13, ?14, ?15
)
RETURNING id, title, slug, content, excerpt, formatter, status, type, is_featured, view_count, published_at, scheduled_at, created_at, updated_at, author_id, thumbnail_path, meta_description, preview_token, preview_expires_at, deleted_at, css, immersive_mode, instagram_share, instagram_status, instagram_media_id, instagram_published_at, instagram_error, instagram_id
`

type CreatePostParams struct {
	Title           string         `json:"title"`
	Slug            string         `json:"slug"`
	Content         string         `json:"content"`
	Excerpt         sql.NullString `json:"excerpt"`
	Formatter       string         `json:"formatter"`
	Status          string         `json:"status"`
	Type            string         `json:"type"`
	IsFeatured      bool           `json:"is_featured"`
	AuthorID        int64          `json:"author_id"`
	ThumbnailPath   sql.NullString `json:"thumbnail_path"`
	MetaDescription sql.NullString `json:"meta_description"`
	ScheduledAt     sql.NullTime   `json:"scheduled_at"`
	Css             string         `json:"css"`
	ImmersiveMode   string         `json:"immersive_mode"`
	InstagramShare  bool           `json:"instagram_share"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.Excerpt,
		arg.Formatter,
		arg.Status,
		arg.Type,
		arg.IsFeatured,
		arg.AuthorID,
		arg.ThumbnailPath,
		arg.MetaDescription,
		arg.ScheduledAt,
		arg.Css,
		arg.ImmersiveMode,
		arg.InstagramShare,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.Formatter,
		&i.Status,
		&i.Type,
		&i.IsFeatured,
		&i.ViewCount,
		&i.PublishedAt,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.ThumbnailPath,
		&i.MetaDescription,
		&i.PreviewToken,
		&i.PreviewExpiresAt,
		&i.DeletedAt,
		&i.Css,
		&i.ImmersiveMode,
		&i.InstagramShare,
		&i.InstagramStatus,
		&i.InstagramMediaID,
		&i.InstagramPublishedAt,
		&i.InstagramError,
		&i.InstagramID,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id, token, ip_address, user_agent, expires_at, created_at, last_activity
) VALUES (
    ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
RETURNING id, user_id, token, ip_address, user_agent, location, created_at, expires_at, last_activity
`

type CreateSessionParams struct {
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	IpAddress string    `json:"ip_address"`
	UserAgent string    `json:"user_agent"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.UserID,
		arg.Token,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.IpAddress,
		&i.UserAgent,
		&i.Location,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastActivity,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (
    name, slug, description, kind, hidden, hides_posts, nav_order,
    in_breadcrumbs, show_related, in_ancestor_flyout, latitude, longitude,
    post_count, created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0, CURRENT_TIMESTAMP
)
RETURNING id, name, slug, description, kind, hidden, hides_posts, nav_order, in_breadcrumbs, show_related, in_ancestor_flyout, latitude, longitude, post_count, created_at
`

type CreateTagParams struct {
	Name             string          `json:"name"`
	Slug             string          `json:"slug"`
	Description      sql.NullString  `json:"description"`
	Kind             string          `json:"kind"`
	Hidden           bool            `json:"hidden"`
	HidesPosts       bool            `json:"hides_posts"`
	NavOrder         sql.NullInt64   `json:"nav_order"`
	InBreadcrumbs    bool            `json:"in_breadcrumbs"`
	ShowRelated      bool            `json:"show_related"`
	InAncestorFlyout bool            `json:"in_ancestor_flyout"`
	Latitude         sql.NullFloat64 `json:"latitude"`
	Longitude        sql.NullFloat64 `json:"longitude"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Kind,
		arg.Hidden,
		arg.HidesPosts,
		arg.NavOrder,
		arg.InBreadcrumbs,
		arg.ShowRelated,
		arg.InAncestorFlyout,
		arg.Latitude,
		arg.Longitude,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Kind,
		&i.Hidden,
		&i.HidesPosts,
		&i.NavOrder,
		&i.InBreadcrumbs,
		&i.ShowRelated,
		&i.InAncestorFlyout,
		&i.Latitude,
		&i.Longitude,
		&i.PostCount,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, email, password_hash, display_name, avatar_path
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, username, email, password_hash, display_name, avatar_path, created_at, last_login
`

type CreateUserParams struct {
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	DisplayName  string         `json:"display_name"`
	AvatarPath   sql.NullString `json:"avatar_path"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.AvatarPath,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarPath,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys
WHERE id = ? AND user_id = ?
`

type DeleteAPIKeyParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, arg.ID, arg.UserID)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media
WHERE id = ?
`

func (q *Queries) DeleteMedia(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMedia, id)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
WHERE id = ? AND author_id = ?
`

type DeletePostParams struct {
	ID       int64 `json:"id"`
	AuthorID int64 `json:"author_id"`
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) error {
	_, err := q.db.ExecContext(ctx, deletePost, arg.ID, arg.AuthorID)
	return err
}

const deletePostTagsByTag = `-- name: DeletePostTagsByTag :exec
DELETE FROM post_tags WHERE tag_id = ?1
`

func (q *Queries) DeletePostTagsByTag(ctx context.Context, tagID int64) error {
	_, err := q.db.ExecContext(ctx, deletePostTagsByTag, tagID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ? AND user_id = ?
`

type DeleteSessionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteSession, arg.ID, arg.UserID)
	return err
}

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM blog_settings
WHERE key = ?
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteSetting, key)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags
WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions
WHERE user_id = ? AND id != ?
`

type DeleteUserSessionsParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) DeleteUserSessions(ctx context.Context, arg DeleteUserSessionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, arg.UserID, arg.ID)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT k.id, k.user_id, k.name, k.key_hash, k.prefix, k.created_at, k.last_used_at, k.expires_at, k.revoked_at, u.username, u.display_name
FROM api_keys k
JOIN users u ON k.user_id = u.id
WHERE k.key_hash = ? AND k.revoked_at IS NULL LIMIT 1
`

type GetAPIKeyByHashRow struct {
	ID          int64        `json:"id"`
	UserID      int64        `json:"user_id"`
	Name        string       `json:"name"`
	KeyHash     string       `json:"key_hash"`
	Prefix      string       `json:"prefix"`
	CreatedAt   time.Time    `json:"created_at"`
	LastUsedAt  sql.NullTime `json:"last_used_at"`
	ExpiresAt   sql.NullTime `json:"expires_at"`
	RevokedAt   sql.NullTime `json:"revoked_at"`
	Username    string       `json:"username"`
	DisplayName string       `json:"display_name"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Username,
		&i.DisplayName,
	)
	return i, err
}

const getFirstUser = `-- name: GetFirstUser :one
SELECT id, username, email, password_hash, display_name, avatar_path, created_at, last_login FROM users
ORDER BY id LIMIT 1
`

func (q *Queries) GetFirstUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getFirstUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarPath,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getMedia = `-- name: GetMedia :one

SELECT id, filename, original_path, thumbnail_path, file_type, mime_type, file_size, width, height, post_id, uploaded_at, checksum, alt_text, caption, metadata, original_metadata, is_public FROM media
WHERE id = ? LIMIT 1
`

// MEDIA
func (q *Queries) GetMedia(ctx context.Context, id int64) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMedia, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalPath,
		&i.ThumbnailPath,
		&i.FileType,
		&i.MimeType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.PostID,
		&i.UploadedAt,
		&i.Checksum,
		&i.AltText,
		&i.Caption,
		&i.Metadata,
		&i.OriginalMetadata,
		&i.IsPublic,
	)
	return i, err
}

const getMediaByChecksum = `-- name: GetMediaByChecksum :one
SELECT id, filename, original_path, thumbnail_path, file_type, mime_type, file_size, width, height, post_id, uploaded_at, checksum, alt_text, caption, metadata, original_metadata, is_public FROM media
WHERE checksum = ? LIMIT 1
`

func (q *Queries) GetMediaByChecksum(ctx context.Context, checksum string) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMediaByChecksum, checksum)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalPath,
		&i.ThumbnailPath,
		&i.FileType,
		&i.MimeType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.PostID,
		&i.UploadedAt,
		&i.Checksum,
		&i.AltText,
		&i.Caption,
		&i.Metadata,
		&i.OriginalMetadata,
		&i.IsPublic,
	)
	return i, err
}

const getMediaByPostID = `-- name: GetMediaByPostID :many
SELECT id, filename, original_path, thumbnail_path, file_type, mime_type, file_size, width, height, post_id, uploaded_at, checksum, alt_text, caption, metadata, original_metadata, is_public FROM media
WHERE post_id = ?
ORDER BY uploaded_at ASC
`

func (q *Queries) GetMediaByPostID(ctx context.Context, postID sql.NullInt64) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, getMediaByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.OriginalPath,
			&i.ThumbnailPath,
			&i.FileType,
			&i.MimeType,
			&i.FileSize,
			&i.Width,
			&i.Height,
			&i.PostID,
			&i.UploadedAt,
			&i.Checksum,
			&i.AltText,
			&i.Caption,
			&i.Metadata,
			&i.OriginalMetadata,
			&i.IsPublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPost = `-- name: GetPost :one

SELECT p.id, p.title, p.slug, p.content, p.excerpt, p.formatter, p.status, p.type, p.is_featured, p.view_count, p.published_at, p.scheduled_at, p.created_at, p.updated_at, p.author_id, p.thumbnail_path, p.meta_description, p.preview_token, p.preview_expires_at, p.deleted_at, p.css, p.immersive_mode, p.instagram_share, p.instagram_status, p.instagram_media_id, p.instagram_published_at, p.instagram_error, p.instagram_id
FROM posts p
WHERE p.id = ? AND p.deleted_at IS NULL LIMIT 1
`

// POSTS
func (q *Queries) GetPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.Formatter,
		&i.Status,
		&i.Type,
		&i.IsFeatured,
		&i.ViewCount,
		&i.PublishedAt,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.ThumbnailPath,
		&i.MetaDescription,
		&i.PreviewToken,
		&i.PreviewExpiresAt,
		&i.DeletedAt,
		&i.Css,
		&i.ImmersiveMode,
		&i.InstagramShare,
		&i.InstagramStatus,
		&i.InstagramMediaID,
		&i.InstagramPublishedAt,
		&i.InstagramError,
		&i.InstagramID,
	)
	return i, err
}

const getPostAnalytics = `-- name: GetPostAnalytics :one
SELECT
    CAST(SUM(view_count) AS INTEGER) as total_views,
    CAST(AVG(view_count) AS FLOAT) as average_views,
    (SELECT id FROM posts WHERE deleted_at IS NULL AND status = 'published' ORDER BY view_count DESC LIMIT 1) as most_viewed_post_id
FROM posts
WHERE deleted_at IS NULL AND status = 'published'
`

type GetPostAnalyticsRow struct {
	TotalViews       int64   `json:"total_views"`
	AverageViews     float64 `json:"average_views"`
	MostViewedPostID int64   `json:"most_viewed_post_id"`
}

func (q *Queries) GetPostAnalytics(ctx context.Context) (GetPostAnalyticsRow, error) {
	row := q.db.QueryRowContext(ctx, getPostAnalytics)
	var i GetPostAnalyticsRow
	err := row.Scan(&i.TotalViews, &i.AverageViews, &i.MostViewedPostID)
	return i, err
}

const getPostBySlug = `-- name: GetPostBySlug :one
SELECT p.id, p.title, p.slug, p.content, p.excerpt, p.formatter, p.status, p.type, p.is_featured, p.view_count, p.published_at, p.scheduled_at, p.created_at, p.updated_at, p.author_id, p.thumbnail_path, p.meta_description, p.preview_token, p.preview_expires_at, p.deleted_at, p.css, p.immersive_mode, p.instagram_share, p.instagram_status, p.instagram_media_id, p.instagram_published_at, p.instagram_error, p.instagram_id
FROM posts p
WHERE p.slug = ? AND p.deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetPostBySlug(ctx context.Context, slug string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostBySlug, slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.Formatter,
		&i.Status,
		&i.Type,
		&i.IsFeatured,
		&i.ViewCount,
		&i.PublishedAt,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.ThumbnailPath,
		&i.MetaDescription,
		&i.PreviewToken,
		&i.PreviewExpiresAt,
		&i.DeletedAt,
		&i.Css,
		&i.ImmersiveMode,
		&i.InstagramShare,
		&i.InstagramStatus,
		&i.InstagramMediaID,
		&i.InstagramPublishedAt,
		&i.InstagramError,
		&i.InstagramID,
	)
	return i, err
}

const getPostsByTag = `-- name: GetPostsByTag :many
WITH RECURSIVE h(id) AS (
    SELECT id FROM tags WHERE hides_posts = 1
    UNION
    SELECT tr.child_id FROM tag_relationships tr JOIN h ON tr.parent_id = h.id
)
SELECT p.id, p.title, p.slug, p.content, p.excerpt, p.formatter, p.status, p.type, p.is_featured, p.view_count, p.published_at, p.scheduled_at, p.created_at, p.updated_at, p.author_id, p.thumbnail_path, p.meta_description, p.preview_token, p.preview_expires_at, p.deleted_at, p.css, p.immersive_mode, p.instagram_share, p.instagram_status, p.instagram_media_id, p.instagram_published_at, p.instagram_error, p.instagram_id
FROM posts p
JOIN post_tags pt ON p.id = pt.post_id
WHERE pt.tag_id = ?1
AND p.deleted_at IS NULL
AND (CASE
    WHEN ?2 THEN 1=1
    WHEN ?3 THEN
        p.status = 'published'
        AND NOT EXISTS (
            SELECT 1 FROM post_tags pt2
            WHERE pt2.post_id = p.id AND pt2.tag_id IN (SELECT id FROM h)
        )
    ELSE p.status IN ('published', 'hidden')
END)
ORDER BY p.published_at DESC, p.created_at DESC
LIMIT ?5 OFFSET ?4
`

type GetPostsByTagParams struct {
	TagID               int64       `json:"tag_id"`
	IncludeDrafts       interface{} `json:"include_drafts"`
	PublishedOnlyFilter interface{} `json:"published_only_filter"`
	Offset              int64       `json:"offset"`
	Limit               int64       `json:"limit"`
}

func (q *Queries) GetPostsByTag(ctx context.Context, arg GetPostsByTagParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByTag,
		arg.TagID,
		arg.IncludeDrafts,
		arg.PublishedOnlyFilter,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Excerpt,
			&i.Formatter,
			&i.Status,
			&i.Type,
			&i.IsFeatured,
			&i.ViewCount,
			&i.PublishedAt,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID,
			&i.ThumbnailPath,
			&i.MetaDescription,
			&i.PreviewToken,
			&i.PreviewExpiresAt,
			&i.DeletedAt,
			&i.Css,
			&i.ImmersiveMode,
			&i.InstagramShare,
			&i.InstagramStatus,
			&i.InstagramMediaID,
			&i.InstagramPublishedAt,
			&i.InstagramError,
		&i.InstagramID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSecret = `-- name: GetSecret :one

SELECT key, value, updated_at FROM blog_secrets WHERE key = ? LIMIT 1
`

// SECRETS
func (q *Queries) GetSecret(ctx context.Context, key string) (BlogSecret, error) {
	row := q.db.QueryRowContext(ctx, getSecret, key)
	var i BlogSecret
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT s.id, s.user_id, s.token, s.ip_address, s.user_agent, s.location, s.created_at, s.expires_at, s.last_activity, u.username, u.display_name
FROM sessions s
JOIN users u ON s.user_id = u.id
WHERE s.token = ? LIMIT 1
`

type GetSessionByTokenRow struct {
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
	Token        string         `json:"token"`
	IpAddress    string         `json:"ip_address"`
	UserAgent    string         `json:"user_agent"`
	Location     sql.NullString `json:"location"`
	CreatedAt    time.Time      `json:"created_at"`
	ExpiresAt    time.Time      `json:"expires_at"`
	LastActivity time.Time      `json:"last_activity"`
	Username     string         `json:"username"`
	DisplayName  string         `json:"display_name"`
}

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.IpAddress,
		&i.UserAgent,
		&i.Location,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastActivity,
		&i.Username,
		&i.DisplayName,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one

SELECT "key", value, value_type, updated_at FROM blog_settings
WHERE key = ? LIMIT 1
`

// SETTINGS
func (q *Queries) GetSetting(ctx context.Context, key string) (BlogSetting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var i BlogSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.ValueType,
		&i.UpdatedAt,
	)
	return i, err
}

const getStorageUsage = `-- name: GetStorageUsage :one
SELECT SUM(file_size) FROM media
`

func (q *Queries) GetStorageUsage(ctx context.Context) (sql.NullFloat64, error) {
	row := q.db.QueryRowContext(ctx, getStorageUsage)
	var sum sql.NullFloat64
	err := row.Scan(&sum)
	return sum, err
}

const getTag = `-- name: GetTag :one

SELECT id, name, slug, description, kind, hidden, hides_posts, nav_order, in_breadcrumbs, show_related, in_ancestor_flyout, latitude, longitude, post_count, created_at FROM tags
WHERE id = ? LIMIT 1
`

// TAGS
func (q *Queries) GetTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Kind,
		&i.Hidden,
		&i.HidesPosts,
		&i.NavOrder,
		&i.InBreadcrumbs,
		&i.ShowRelated,
		&i.InAncestorFlyout,
		&i.Latitude,
		&i.Longitude,
		&i.PostCount,
		&i.CreatedAt,
	)
	return i, err
}

const getTagBySlug = `-- name: GetTagBySlug :one
SELECT id, name, slug, description, kind, hidden, hides_posts, nav_order, in_breadcrumbs, show_related, in_ancestor_flyout, latitude, longitude, post_count, created_at FROM tags
WHERE slug = ? LIMIT 1
`

func (q *Queries) GetTagBySlug(ctx context.Context, slug string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagBySlug, slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Kind,
		&i.Hidden,
		&i.HidesPosts,
		&i.NavOrder,
		&i.InBreadcrumbs,
		&i.ShowRelated,
		&i.InAncestorFlyout,
		&i.Latitude,
		&i.Longitude,
		&i.PostCount,
		&i.CreatedAt,
	)
	return i, err
}

const getTagChildren = `-- name: GetTagChildren :many
SELECT t.id, t.name, t.slug, t.description, t.kind, t.hidden, t.hides_posts, t.nav_order, t.in_breadcrumbs, t.show_related, t.in_ancestor_flyout, t.latitude, t.longitude, t.post_count, t.created_at FROM tags t
JOIN tag_relationships tr ON t.id = tr.child_id
WHERE tr.parent_id = ?
`

func (q *Queries) GetTagChildren(ctx context.Context, parentID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Kind,
			&i.Hidden,
			&i.HidesPosts,
			&i.NavOrder,
			&i.InBreadcrumbs,
			&i.ShowRelated,
			&i.InAncestorFlyout,
			&i.Latitude,
			&i.Longitude,
			&i.PostCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagParents = `-- name: GetTagParents :many

SELECT t.id, t.name, t.slug, t.description, t.kind, t.hidden, t.hides_posts, t.nav_order, t.in_breadcrumbs, t.show_related, t.in_ancestor_flyout, t.latitude, t.longitude, t.post_count, t.created_at FROM tags t
JOIN tag_relationships tr ON t.id = tr.parent_id
WHERE tr.child_id = ?
`

// HIERARCHY
func (q *Queries) GetTagParents(ctx context.Context, childID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagParents, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Kind,
			&i.Hidden,
			&i.HidesPosts,
			&i.NavOrder,
			&i.InBreadcrumbs,
			&i.ShowRelated,
			&i.InAncestorFlyout,
			&i.Latitude,
			&i.Longitude,
			&i.PostCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsForPost = `-- name: GetTagsForPost :many
SELECT t.id, t.name, t.slug, t.description, t.kind, t.hidden, t.hides_posts, t.nav_order, t.in_breadcrumbs, t.show_related, t.in_ancestor_flyout, t.latitude, t.longitude, t.post_count, t.created_at FROM tags t
JOIN post_tags pt ON t.id = pt.tag_id
WHERE pt.post_id = ?
ORDER BY t.name ASC
`

func (q *Queries) GetTagsForPost(ctx context.Context, postID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Kind,
			&i.Hidden,
			&i.HidesPosts,
			&i.NavOrder,
			&i.InBreadcrumbs,
			&i.ShowRelated,
			&i.InAncestorFlyout,
			&i.Latitude,
			&i.Longitude,
			&i.PostCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, password_hash, display_name, avatar_path, created_at, last_login FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarPath,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, display_name, avatar_path, created_at, last_login FROM users
WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarPath,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, display_name, avatar_path, created_at, last_login FROM users
WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarPath,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getUserSessions = `-- name: GetUserSessions :many
SELECT id, user_id, token, ip_address, user_agent, location, created_at, expires_at, last_activity FROM sessions
WHERE user_id = ?
ORDER BY last_activity DESC
`

func (q *Queries) GetUserSessions(ctx context.Context, userID int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.IpAddress,
			&i.UserAgent,
			&i.Location,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementPostViewCount = `-- name: IncrementPostViewCount :exec
UPDATE posts
SET view_count = view_count + 1
WHERE id = ?
`

func (q *Queries) IncrementPostViewCount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementPostViewCount, id)
	return err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, user_id, name, key_hash, prefix, created_at, last_used_at, expires_at, revoked_at FROM api_keys
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID int64) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.Prefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedia = `-- name: ListMedia :many
SELECT id, filename, original_path, thumbnail_path, file_type, mime_type, file_size, width, height, post_id, uploaded_at, checksum, alt_text, caption, metadata, original_metadata, is_public FROM media
WHERE (CASE WHEN ?1 THEN file_type = ?2 ELSE 1=1 END)
ORDER BY uploaded_at DESC
LIMIT ?4 OFFSET ?3
`

type ListMediaParams struct {
	TypeFilter interface{} `json:"type_filter"`
	FileType   string      `json:"file_type"`
	Offset     int64       `json:"offset"`
	Limit      int64       `json:"limit"`
}

func (q *Queries) ListMedia(ctx context.Context, arg ListMediaParams) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listMedia,
		arg.TypeFilter,
		arg.FileType,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.OriginalPath,
			&i.ThumbnailPath,
			&i.FileType,
			&i.MimeType,
			&i.FileSize,
			&i.Width,
			&i.Height,
			&i.PostID,
			&i.UploadedAt,
			&i.Checksum,
			&i.AltText,
			&i.Caption,
			&i.Metadata,
			&i.OriginalMetadata,
			&i.IsPublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
WITH RECURSIVE h(id) AS (
    SELECT id FROM tags WHERE hides_posts = 1
    UNION
    SELECT tr.child_id FROM tag_relationships tr JOIN h ON tr.parent_id = h.id
)
SELECT p.id, p.title, p.slug, p.content, p.excerpt, p.formatter, p.status, p.type, p.is_featured, p.view_count, p.published_at, p.scheduled_at, p.created_at, p.updated_at, p.author_id, p.thumbnail_path, p.meta_description, p.preview_token, p.preview_expires_at, p.deleted_at, p.css, p.immersive_mode, p.instagram_share, p.instagram_status, p.instagram_media_id, p.instagram_published_at, p.instagram_error, p.instagram_id
FROM posts p
WHERE
    p.deleted_at IS NULL
    AND p.type != 'page'
    AND (CASE WHEN ?1 THEN p.status = ?2 ELSE 1=1 END)
    AND (CASE WHEN ?3 THEN p.is_featured = 1 ELSE 1=1 END)
    AND (CASE
        WHEN ?4 THEN 1=1
        WHEN ?5 THEN p.status IN ('published', 'hidden')
        ELSE p.status = 'published'
    END)

    AND (CASE
        WHEN ?4 THEN 1=1
        WHEN ?5 THEN 1=1
        ELSE p.id NOT IN (
            SELECT pt.post_id FROM post_tags pt
            WHERE pt.tag_id IN (SELECT id FROM h)
        )
    END)
ORDER BY p.published_at DESC, p.created_at DESC
LIMIT ?7 OFFSET ?6
`

type ListPostsParams struct {
	StatusFilter   interface{} `json:"status_filter"`
	Status         string      `json:"status"`
	FeaturedFilter interface{} `json:"featured_filter"`
	IncludeDrafts  interface{} `json:"include_drafts"`
	IncludeHidden  interface{} `json:"include_hidden"`
	Offset         int64       `json:"offset"`
	Limit          int64       `json:"limit"`
	// IncludePages, when true, keeps type=page rows in results (admin views).
	// Consumed by the hand-written sqliteRepository.ListPosts override.
	IncludePages bool `json:"include_pages"`
	// IncludeContent, when true, selects the full content body. List/grid views
	// leave it false (they use media_url); the offline snapshot sets it true.
	// Consumed by the hand-written sqliteRepository.ListPosts override.
	IncludeContent bool `json:"include_content"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts,
		arg.StatusFilter,
		arg.Status,
		arg.FeaturedFilter,
		arg.IncludeDrafts,
		arg.IncludeHidden,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Excerpt,
			&i.Formatter,
			&i.Status,
			&i.Type,
			&i.IsFeatured,
			&i.ViewCount,
			&i.PublishedAt,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID,
			&i.ThumbnailPath,
			&i.MetaDescription,
			&i.PreviewToken,
			&i.PreviewExpiresAt,
			&i.DeletedAt,
			&i.Css,
			&i.ImmersiveMode,
			&i.InstagramShare,
			&i.InstagramStatus,
			&i.InstagramMediaID,
			&i.InstagramPublishedAt,
			&i.InstagramError,
		&i.InstagramID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByViews = `-- name: ListPostsByViews :many
WITH RECURSIVE h(id) AS (
    SELECT id FROM tags WHERE hides_posts = 1
    UNION
    SELECT tr.child_id FROM tag_relationships tr JOIN h ON tr.parent_id = h.id
)
SELECT p.id, p.title, p.slug, p.content, p.excerpt, p.formatter, p.status, p.type, p.is_featured, p.view_count, p.published_at, p.scheduled_at, p.created_at, p.updated_at, p.author_id, p.thumbnail_path, p.meta_description, p.preview_token, p.preview_expires_at, p.deleted_at, p.css, p.immersive_mode, p.instagram_share, p.instagram_status, p.instagram_media_id, p.instagram_published_at, p.instagram_error, p.instagram_id
FROM posts p
WHERE
    p.deleted_at IS NULL
    AND p.type != 'page'
    AND (CASE WHEN ?1 THEN p.status = ?2 ELSE 1=1 END)
    AND (CASE WHEN ?3 THEN p.is_featured = 1 ELSE 1=1 END)
    AND (CASE
        WHEN ?4 THEN 1=1
        WHEN ?5 THEN p.status IN ('published', 'hidden')
        ELSE p.status = 'published'
    END)

    AND (CASE
        WHEN ?4 THEN 1=1
        WHEN ?5 THEN 1=1
        ELSE p.id NOT IN (
            SELECT pt.post_id FROM post_tags pt
            WHERE pt.tag_id IN (SELECT id FROM h)
        )
    END)
ORDER BY p.view_count DESC, p.published_at DESC
LIMIT ?7 OFFSET ?6
`

type ListPostsByViewsParams struct {
	StatusFilter   interface{} `json:"status_filter"`
	Status         string      `json:"status"`
	FeaturedFilter interface{} `json:"featured_filter"`
	IncludeDrafts  interface{} `json:"include_drafts"`
	IncludeHidden  interface{} `json:"include_hidden"`
	Offset         int64       `json:"offset"`
	Limit          int64       `json:"limit"`
}

func (q *Queries) ListPostsByViews(ctx context.Context, arg ListPostsByViewsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPostsByViews,
		arg.StatusFilter,
		arg.Status,
		arg.FeaturedFilter,
		arg.IncludeDrafts,
		arg.IncludeHidden,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Excerpt,
			&i.Formatter,
			&i.Status,
			&i.Type,
			&i.IsFeatured,
			&i.ViewCount,
			&i.PublishedAt,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID,
			&i.ThumbnailPath,
			&i.MetaDescription,
			&i.PreviewToken,
			&i.PreviewExpiresAt,
			&i.DeletedAt,
			&i.Css,
			&i.ImmersiveMode,
			&i.InstagramShare,
			&i.InstagramStatus,
			&i.InstagramMediaID,
			&i.InstagramPublishedAt,
			&i.InstagramError,
		&i.InstagramID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettings = `-- name: ListSettings :many
SELECT "key", value, value_type, updated_at FROM blog_settings
`

func (q *Queries) ListSettings(ctx context.Context) ([]BlogSetting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlogSetting
	for rows.Next() {
		var i BlogSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.ValueType,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, slug, description, kind, hidden, hides_posts, nav_order, in_breadcrumbs, show_related, in_ancestor_flyout, latitude, longitude, post_count, created_at FROM tags
WHERE (CASE WHEN ?1 THEN 1=1 ELSE post_count > 0 END)
ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context, includeEmptyFilter interface{}) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags, includeEmptyFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Kind,
			&i.Hidden,
			&i.HidesPosts,
			&i.NavOrder,
			&i.InBreadcrumbs,
			&i.ShowRelated,
			&i.InAncestorFlyout,
			&i.Latitude,
			&i.Longitude,
			&i.PostCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedPosts = `-- name: ListTrashedPosts :many
SELECT id, title, slug, content, excerpt, formatter, status, type, is_featured, view_count, published_at, scheduled_at, created_at, updated_at, author_id, thumbnail_path, meta_description, preview_token, preview_expires_at, deleted_at, css, immersive_mode, instagram_share, instagram_status, instagram_media_id, instagram_published_at, instagram_error, instagram_id FROM posts
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC
LIMIT ? OFFSET ?
`

type ListTrashedPostsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListTrashedPosts(ctx context.Context, arg ListTrashedPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listTrashedPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Excerpt,
			&i.Formatter,
			&i.Status,
			&i.Type,
			&i.IsFeatured,
			&i.ViewCount,
			&i.PublishedAt,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID,
			&i.ThumbnailPath,
			&i.MetaDescription,
			&i.PreviewToken,
			&i.PreviewExpiresAt,
			&i.DeletedAt,
			&i.Css,
			&i.ImmersiveMode,
			&i.InstagramShare,
			&i.InstagramStatus,
			&i.InstagramMediaID,
			&i.InstagramPublishedAt,
			&i.InstagramError,
		&i.InstagramID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergePostTags = `-- name: MergePostTags :exec
UPDATE OR IGNORE post_tags SET tag_id = ?1
WHERE tag_id = ?2
`

type MergePostTagsParams struct {
	WinnerID int64 `json:"winner_id"`
	LoserID  int64 `json:"loser_id"`
}

func (q *Queries) MergePostTags(ctx context.Context, arg MergePostTagsParams) error {
	_, err := q.db.ExecContext(ctx, mergePostTags, arg.WinnerID, arg.LoserID)
	return err
}

const mergeTagChildren = `-- name: MergeTagChildren :exec
UPDATE OR IGNORE tag_relationships SET parent_id = ?1
WHERE parent_id = ?2
`

type MergeTagChildrenParams struct {
	WinnerID int64 `json:"winner_id"`
	LoserID  int64 `json:"loser_id"`
}

func (q *Queries) MergeTagChildren(ctx context.Context, arg MergeTagChildrenParams) error {
	_, err := q.db.ExecContext(ctx, mergeTagChildren, arg.WinnerID, arg.LoserID)
	return err
}

const mergeTagParents = `-- name: MergeTagParents :exec
UPDATE OR IGNORE tag_relationships SET child_id = ?1
WHERE child_id = ?2
`

type MergeTagParentsParams struct {
	WinnerID int64 `json:"winner_id"`
	LoserID  int64 `json:"loser_id"`
}

func (q *Queries) MergeTagParents(ctx context.Context, arg MergeTagParentsParams) error {
	_, err := q.db.ExecContext(ctx, mergeTagParents, arg.WinnerID, arg.LoserID)
	return err
}

const publishPost = `-- name: PublishPost :one
UPDATE posts
SET status = 'published', published_at = COALESCE(published_at, CURRENT_TIMESTAMP), updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, title, slug, content, excerpt, formatter, status, type, is_featured, view_count, published_at, scheduled_at, created_at, updated_at, author_id, thumbnail_path, meta_description, preview_token, preview_expires_at, deleted_at, css, immersive_mode, instagram_share, instagram_status, instagram_media_id, instagram_published_at, instagram_error, instagram_id
`

func (q *Queries) PublishPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, publishPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.Formatter,
		&i.Status,
		&i.Type,
		&i.IsFeatured,
		&i.ViewCount,
		&i.PublishedAt,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.ThumbnailPath,
		&i.MetaDescription,
		&i.PreviewToken,
		&i.PreviewExpiresAt,
		&i.DeletedAt,
		&i.Css,
		&i.ImmersiveMode,
		&i.InstagramShare,
		&i.InstagramStatus,
		&i.InstagramMediaID,
		&i.InstagramPublishedAt,
		&i.InstagramError,
		&i.InstagramID,
	)
	return i, err
}

const removeTagFromPost = `-- name: RemoveTagFromPost :exec
DELETE FROM post_tags
WHERE post_id = ? AND tag_id = ?
`

type RemoveTagFromPostParams struct {
	PostID int64 `json:"post_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) RemoveTagFromPost(ctx context.Context, arg RemoveTagFromPostParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromPost, arg.PostID, arg.TagID)
	return err
}

const removeTagRelationship = `-- name: RemoveTagRelationship :exec
DELETE FROM tag_relationships
WHERE parent_id = ? AND child_id = ?
`

type RemoveTagRelationshipParams struct {
	ParentID int64 `json:"parent_id"`
	ChildID  int64 `json:"child_id"`
}

func (q *Queries) RemoveTagRelationship(ctx context.Context, arg RemoveTagRelationshipParams) error {
	_, err := q.db.ExecContext(ctx, removeTagRelationship, arg.ParentID, arg.ChildID)
	return err
}

const restorePost = `-- name: RestorePost :exec
UPDATE posts
SET deleted_at = NULL
WHERE id = ? AND author_id = ?
`

type RestorePostParams struct {
	ID       int64 `json:"id"`
	AuthorID int64 `json:"author_id"`
}

func (q *Queries) RestorePost(ctx context.Context, arg RestorePostParams) error {
	_, err := q.db.ExecContext(ctx, restorePost, arg.ID, arg.AuthorID)
	return err
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys
SET revoked_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type RevokeAPIKeyParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, revokeAPIKey, arg.ID, arg.UserID)
	return err
}

const setPostPreviewToken = `-- name: SetPostPreviewToken :exec
UPDATE posts
SET preview_token = ?, preview_expires_at = ?
WHERE id = ?
`

type SetPostPreviewTokenParams struct {
	PreviewToken     sql.NullString `json:"preview_token"`
	PreviewExpiresAt sql.NullTime   `json:"preview_expires_at"`
	ID               int64          `json:"id"`
}

func (q *Queries) SetPostPreviewToken(ctx context.Context, arg SetPostPreviewTokenParams) error {
	_, err := q.db.ExecContext(ctx, setPostPreviewToken, arg.PreviewToken, arg.PreviewExpiresAt, arg.ID)
	return err
}

const softDeletePost = `-- name: SoftDeletePost :exec
UPDATE posts
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ? AND author_id = ? AND deleted_at IS NULL
`

type SoftDeletePostParams struct {
	ID       int64 `json:"id"`
	AuthorID int64 `json:"author_id"`
}

func (q *Queries) SoftDeletePost(ctx context.Context, arg SoftDeletePostParams) error {
	_, err := q.db.ExecContext(ctx, softDeletePost, arg.ID, arg.AuthorID)
	return err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchAPIKeyLastUsed, id)
	return err
}

const updateAllTagPostCounts = `-- name: UpdateAllTagPostCounts :exec
UPDATE tags
SET post_count = (
    SELECT COUNT(*) FROM post_tags
    JOIN posts ON post_tags.post_id = posts.id
    WHERE tag_id = tags.id AND posts.status != 'draft' AND posts.deleted_at IS NULL
)
`

func (q *Queries) UpdateAllTagPostCounts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateAllTagPostCounts)
	return err
}

const updateMedia = `-- name: UpdateMedia :one
UPDATE media
SET alt_text = COALESCE(?, alt_text),
    caption = COALESCE(?, caption),
    post_id = COALESCE(?, post_id),
    metadata = COALESCE(?, metadata)
WHERE id = ?
RETURNING id, filename, original_path, thumbnail_path, file_type, mime_type, file_size, width, height, post_id, uploaded_at, checksum, alt_text, caption, metadata, original_metadata, is_public
`

type UpdateMediaParams struct {
	AltText  sql.NullString `json:"alt_text"`
	Caption  sql.NullString `json:"caption"`
	PostID   sql.NullInt64  `json:"post_id"`
	Metadata sql.NullString `json:"metadata"`
	ID       int64          `json:"id"`
}

func (q *Queries) UpdateMedia(ctx context.Context, arg UpdateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, updateMedia,
		arg.AltText,
		arg.Caption,
		arg.PostID,
		arg.Metadata,
		arg.ID,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalPath,
		&i.ThumbnailPath,
		&i.FileType,
		&i.MimeType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.PostID,
		&i.UploadedAt,
		&i.Checksum,
		&i.AltText,
		&i.Caption,
		&i.Metadata,
		&i.OriginalMetadata,
		&i.IsPublic,
	)
	return i, err
}

const updateMediaFilename = `-- name: UpdateMediaFilename :one
UPDATE media
SET filename = ?, original_path = ?, thumbnail_path = ?
WHERE id = ?
RETURNING id, filename, original_path, thumbnail_path, file_type, mime_type, file_size, width, height, post_id, uploaded_at, checksum, alt_text, caption, metadata, original_metadata, is_public
`

type UpdateMediaFilenameParams struct {
	Filename      string         `json:"filename"`
	OriginalPath  string         `json:"original_path"`
	ThumbnailPath sql.NullString `json:"thumbnail_path"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateMediaFilename(ctx context.Context, arg UpdateMediaFilenameParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, updateMediaFilename,
		arg.Filename,
		arg.OriginalPath,
		arg.ThumbnailPath,
		arg.ID,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalPath,
		&i.ThumbnailPath,
		&i.FileType,
		&i.MimeType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.PostID,
		&i.UploadedAt,
		&i.Checksum,
		&i.AltText,
		&i.Caption,
		&i.Metadata,
		&i.OriginalMetadata,
		&i.IsPublic,
	)
	return i, err
}

const updateMediaMetadata = `-- name: UpdateMediaMetadata :one
UPDATE media
SET metadata = ?
WHERE id = ?
RETURNING id, filename, original_path, thumbnail_path, file_type, mime_type, file_size, width, height, post_id, uploaded_at, checksum, alt_text, caption, metadata, original_metadata, is_public
`

type UpdateMediaMetadataParams struct {
	Metadata sql.NullString `json:"metadata"`
	ID       int64          `json:"id"`
}

func (q *Queries) UpdateMediaMetadata(ctx context.Context, arg UpdateMediaMetadataParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, updateMediaMetadata, arg.Metadata, arg.ID)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalPath,
		&i.ThumbnailPath,
		&i.FileType,
		&i.MimeType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.PostID,
		&i.UploadedAt,
		&i.Checksum,
		&i.AltText,
		&i.Caption,
		&i.Metadata,
		&i.OriginalMetadata,
		&i.IsPublic,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET title = ?1, slug = ?2, content = ?3, excerpt = ?4, formatter = ?5, status = ?6, type = ?7, is_featured = ?8, thumbnail_path = ?9, meta_description = ?10,
    scheduled_at = ?11,
    published_at = (CASE
        WHEN ?6 = 'published' THEN COALESCE(published_at, CURRENT_TIMESTAMP)
        WHEN ?6 = 'scheduled'  THEN NULL
        ELSE published_at
    END),
    css = ?12,
    immersive_mode = ?13,
    instagram_share = ?14,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?15 AND author_id = ?16
RETURNING id, title, slug, content, excerpt, formatter, status, type, is_featured, view_count, published_at, scheduled_at, created_at, updated_at, author_id, thumbnail_path, meta_description, preview_token, preview_expires_at, deleted_at, css, immersive_mode, instagram_share, instagram_status, instagram_media_id, instagram_published_at, instagram_error, instagram_id
`

type UpdatePostParams struct {
	Title           string         `json:"title"`
	Slug            string         `json:"slug"`
	Content         string         `json:"content"`
	Excerpt         sql.NullString `json:"excerpt"`
	Formatter       string         `json:"formatter"`
	Status          string         `json:"status"`
	Type            string         `json:"type"`
	IsFeatured      bool           `json:"is_featured"`
	ThumbnailPath   sql.NullString `json:"thumbnail_path"`
	MetaDescription sql.NullString `json:"meta_description"`
	ScheduledAt     sql.NullTime   `json:"scheduled_at"`
	Css             string         `json:"css"`
	ImmersiveMode   string         `json:"immersive_mode"`
	InstagramShare  bool           `json:"instagram_share"`
	ID              int64          `json:"id"`
	AuthorID        int64          `json:"author_id"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, updatePost,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.Excerpt,
		arg.Formatter,
		arg.Status,
		arg.Type,
		arg.IsFeatured,
		arg.ThumbnailPath,
		arg.MetaDescription,
		arg.ScheduledAt,
		arg.Css,
		arg.ImmersiveMode,
		arg.InstagramShare,
		arg.ID,
		arg.AuthorID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.Formatter,
		&i.Status,
		&i.Type,
		&i.IsFeatured,
		&i.ViewCount,
		&i.PublishedAt,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.ThumbnailPath,
		&i.MetaDescription,
		&i.PreviewToken,
		&i.PreviewExpiresAt,
		&i.DeletedAt,
		&i.Css,
		&i.ImmersiveMode,
		&i.InstagramShare,
		&i.InstagramStatus,
		&i.InstagramMediaID,
		&i.InstagramPublishedAt,
		&i.InstagramError,
		&i.InstagramID,
	)
	return i, err
}

const updatePostInstagramStatus = `-- name: UpdatePostInstagramStatus :exec
UPDATE posts
SET instagram_status = ?,
    instagram_media_id = ?,
    instagram_published_at = ?,
    instagram_error = ?
WHERE id = ?
`

type UpdatePostInstagramStatusParams struct {
	InstagramStatus      string         `json:"instagram_status"`
	InstagramMediaID     sql.NullString `json:"instagram_media_id"`
	InstagramPublishedAt sql.NullTime   `json:"instagram_published_at"`
	InstagramError       sql.NullString `json:"instagram_error"`
	ID                   int64          `json:"id"`
}

func (q *Queries) UpdatePostInstagramStatus(ctx context.Context, arg UpdatePostInstagramStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePostInstagramStatus,
		arg.InstagramStatus,
		arg.InstagramMediaID,
		arg.InstagramPublishedAt,
		arg.InstagramError,
		arg.ID,
	)
	return err
}

const updateSessionActivity = `-- name: UpdateSessionActivity :exec
UPDATE sessions
SET last_activity = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateSessionActivity(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateSessionActivity, id)
	return err
}

const updateSetting = `-- name: UpdateSetting :one
INSERT INTO blog_settings (key, value, value_type, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(key) DO UPDATE SET
    value = excluded.value,
    value_type = excluded.value_type,
    updated_at = CURRENT_TIMESTAMP
RETURNING "key", value, value_type, updated_at
`

type UpdateSettingParams struct {
	Key       string         `json:"key"`
	Value     sql.NullString `json:"value"`
	ValueType string         `json:"value_type"`
}

func (q *Queries) UpdateSetting(ctx context.Context, arg UpdateSettingParams) (BlogSetting, error) {
	row := q.db.QueryRowContext(ctx, updateSetting, arg.Key, arg.Value, arg.ValueType)
	var i BlogSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.ValueType,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name = ?, slug = ?, description = ?,
    kind = ?, hidden = ?, hides_posts = ?, nav_order = ?,
    in_breadcrumbs = ?, show_related = ?, in_ancestor_flyout = ?,
    latitude = ?, longitude = ?
WHERE id = ?
RETURNING id, name, slug, description, kind, hidden, hides_posts, nav_order, in_breadcrumbs, show_related, in_ancestor_flyout, latitude, longitude, post_count, created_at
`

type UpdateTagParams struct {
	Name             string          `json:"name"`
	Slug             string          `json:"slug"`
	Description      sql.NullString  `json:"description"`
	Kind             string          `json:"kind"`
	Hidden           bool            `json:"hidden"`
	HidesPosts       bool            `json:"hides_posts"`
	NavOrder         sql.NullInt64   `json:"nav_order"`
	InBreadcrumbs    bool            `json:"in_breadcrumbs"`
	ShowRelated      bool            `json:"show_related"`
	InAncestorFlyout bool            `json:"in_ancestor_flyout"`
	Latitude         sql.NullFloat64 `json:"latitude"`
	Longitude        sql.NullFloat64 `json:"longitude"`
	ID               int64           `json:"id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, updateTag,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Kind,
		arg.Hidden,
		arg.HidesPosts,
		arg.NavOrder,
		arg.InBreadcrumbs,
		arg.ShowRelated,
		arg.InAncestorFlyout,
		arg.Latitude,
		arg.Longitude,
		arg.ID,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Kind,
		&i.Hidden,
		&i.HidesPosts,
		&i.NavOrder,
		&i.InBreadcrumbs,
		&i.ShowRelated,
		&i.InAncestorFlyout,
		&i.Latitude,
		&i.Longitude,
		&i.PostCount,
		&i.CreatedAt,
	)
	return i, err
}

const updateTagPostCount = `-- name: UpdateTagPostCount :exec
UPDATE tags
SET post_count = (
    SELECT COUNT(*) FROM post_tags
    JOIN posts ON post_tags.post_id = posts.id
    WHERE post_tags.tag_id = tags.id AND posts.status != 'draft' AND posts.deleted_at IS NULL
)
WHERE tags.id = ?
`

func (q *Queries) UpdateTagPostCount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateTagPostCount, id)
	return err
}

const updateUserLogin = `-- name: UpdateUserLogin :exec
UPDATE users
SET last_login = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateUserLogin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateUserLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = ?
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const upsertSecret = `-- name: UpsertSecret :exec
INSERT INTO blog_secrets (key, value, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
`

type UpsertSecretParams struct {
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}

func (q *Queries) UpsertSecret(ctx context.Context, arg UpsertSecretParams) error {
	_, err := q.db.ExecContext(ctx, upsertSecret, arg.Key, arg.Value)
	return err
}

const withdrawPost = `-- name: WithdrawPost :one
UPDATE posts
SET status = 'draft', updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, title, slug, content, excerpt, formatter, status, type, is_featured, view_count, published_at, scheduled_at, created_at, updated_at, author_id, thumbnail_path, meta_description, preview_token, preview_expires_at, deleted_at, css, immersive_mode, instagram_share, instagram_status, instagram_media_id, instagram_published_at, instagram_error, instagram_id
`

func (q *Queries) WithdrawPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, withdrawPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.Formatter,
		&i.Status,
		&i.Type,
		&i.IsFeatured,
		&i.ViewCount,
		&i.PublishedAt,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.ThumbnailPath,
		&i.MetaDescription,
		&i.PreviewToken,
		&i.PreviewExpiresAt,
		&i.DeletedAt,
		&i.Css,
		&i.ImmersiveMode,
		&i.InstagramShare,
		&i.InstagramStatus,
		&i.InstagramMediaID,
		&i.InstagramPublishedAt,
		&i.InstagramError,
		&i.InstagramID,
	)
	return i, err
}
